- name: Install nginx
  hosts: frontend
  become: yes #By adding become=yes it will execute with sudo user


  tasks:
  - name: Install nginx 
    ansible.builtin.package:   # we will be adding pacakge because it will automatically detect operating system 
      name: nginx
      state: present # to install the pacakge give present to delete the package give absent


  
  - name: Starting nginx service
    ansible.builtin.service: # service is to start or ennable or reload or restart the service
      name: nginx
      state: started
      enabled: yes # it is to enable the service






  
# - name: install nginx
#   hosts: local
#   connection: local
#   become: yes
#   tasks:
#   - name: install nginx
#     ansible.builtin.package:
#       name: nginx
#       state: present

#   - name: start nginx
#     ansible.builtin.service:
#       name: nginx
#       state: started
#       enabled: yes
